research_task:
  description: >
    Conduct a comprehensive analysis of the latest advancements in AI in 2025. 
    Identify key trends, breakthrough technologies, and potential industry impacts. 
    Compile your findings in a detailed report. 
    Make sure to check with a human if the draft is good before finalizing your answer.
  expected_output: >
    A comprehensive full report on the latest AI advancements in 2025, leave nothing out
  agent: researcher
  human_input: True

writing_task:
  description: >
    Using the insights from the researcher\'s report, develop an engaging blog post that highlights the most significant AI advancements. 
    Your post should be informative yet accessible, catering to a tech-savvy audience. 
    Aim for a narrative that captures the essence of these breakthroughs and their implications for the future.
  expected_output: >
    A compelling 3 paragraphs blog post formatted as markdown about the latest AI advancements in 2025
  agent: writer
  human_input: True